Date field
mini-pw/PvSTATEM pull request #158
Opened 2024-10-04 17:22 UTC by ZetrextJG

Add `plate_datetime` field to a Plate object and extend parsers to support that.
Reorder fields in Plate, PlateBuilder to match each other.
Prettify docs a little bit

2024-10-04 19:19 UTC, Fersoil commented
please add tests to improve the coverage

2024-10-08 17:02 UTC, Fersoil requested changes

2024-10-09 11:16 UTC, ZetrextJG commented
Bug noticed during PR #164

2024-10-09 13:05 UTC, Fersoil approved these changes
LGTM

2024-10-09 13:05 UTC, merged