Rename predicted dilution values to RAU
mini-pw/PvSTATEM pull request #171
Opened 2024-10-10 14:29 UTC by ZetrextJG

Change the way we name predicted dilution. When we use the Richard equation to predict the dilution instead of output that to a user we change the name to RAU and multiply the prediction by 1_000_000 to make it easier to interpret. On log scale that multiplication is just a shift of the values, so the plots stay relatively the same.

Additional things is that PR:
- Update vignettes to comply with the new naming
- Change how much of the SC curve we display for the user slightly as not to overcrowd the X axis.
- Implement cutting of predicted RAU with MFI above the the max MFI of the standard curve samples. Allow the user to specify how much above that value the extrapolation can happen. #TODO: Suppress the warnings from the nplr::getEstimates
- Move pkgdown from Bootstrap 3 to 5 as the version 3 is deprecated.
- Mark `handle_datetime` as a internal function

This PR will resolve #170 ( and #149  to some extend)

2024-10-10 15:18 UTC, Fersoil requested changes
Looks good, only few missed dilutions. Add reference and docs

2024-10-10 15:18 UTC, Fersoil commented on R/classes-model.R
>  #' @export
this S3 method also requires the documentation change

2024-10-10 15:18 UTC, Fersoil commented on R/classes-model.R
inside the Model instance there should be explained the difference between dilution and RAU - input and prediction. Even for me this is quite confusing. I would propose that the majority of explanations might be inside the vignettes and Models doc could simply refer to that page

2024-10-10 15:18 UTC, Fersoil commented on R/plots-standard_curve.R
>  #' @param log_scale Which elements on the plot should be displayed in log scale. By default `"dilutions"`. If `NULL` or `c()` no log scale is used, if `"all"` or `c("dilutions", "MFI")` all elements
dilutions->RAU

2024-10-10 15:18 UTC, Fersoil commented on R/process-plate.R
reference of this function contains dilutions instead of RAU. 


My suggestion:
```
Compute dilutions for each analyte using the corresponding model.
````
should be changed to 
```
Predict RAU for each analyte using the corresponding model.
````

2024-10-11 12:29 UTC, ZetrextJG commented on R/plots-standard_curve.R
>  #' @param log_scale Which elements on the plot should be displayed in log scale. By default `"all"`. If `NULL` or `c()` no log scale is used, if `"all"` or `c("dilutions", "MFI")` all elements are di
Changed

2024-10-11 12:29 UTC, ZetrextJG commented on R/plots-standard_curve.R
>  #' @param log_scale Which elements on the plot should be displayed in log scale. By default `"dilutions"`. If `NULL` or `c()` no log scale is used, if `"all"` or `c("dilutions", "MFI")` all elements
Changed

2024-10-11 13:17 UTC, ZetrextJG commented on R/process-plate.R
I have changed a lot in the description of that `process_plate`.

2024-10-11 17:22 UTC, ZetrextJG commented on R/classes-model.R
Done

2024-10-11 17:22 UTC, ZetrextJG commented on vignettes/example_script.Rmd
Done

2024-10-13 09:37 UTC, Fersoil approved these changes
now it looks good

2024-10-13 09:38 UTC, merged