Encapsulate model
mini-pw/PvSTATEM pull request #76
Opened 2024-08-12 12:07 UTC by ZetrextJG

2024-08-13 16:28 UTC, Fersoil requested changes

2024-08-13 16:28 UTC, Fersoil commented on R/model.R
> +SCModel <- R6::R6Class(
add function printing the model contents and parameters. The method `print` is in my opinion required

2024-08-13 16:28 UTC, Fersoil commented on R/standard_curves.R
The standard curve plot is quite eye-pleasing, but it is missing some elements Michael requires. 

I suggest we open a separate issue to meet those guidelines, but I am writing it down so that it doesn't get missed.

We need to include the blank MFI value (which could be represented as a solid line below all the standard curve samples) and horizontal lines for the highest and lowest dilutions.

Additionally, we can add the model predictions to the plot, represented as dots, to verify if all the predicted dilutions are contained within the biggest slope of the standard curve

2024-08-13 16:28 UTC, Fersoil commented on R/model.R
> +    predict = function(mfi) {
missing docs

2024-08-13 16:28 UTC, Fersoil commented on R/model.R
> +    top_asymptote = function() {
I would move this into the `active` part of the class, it is not a typical method, but rather a field. Also missing docs

2024-08-13 16:28 UTC, Fersoil commented on R/model.R
> +    bottom_asymptote = function() {
this is also a field imo

2024-08-13 16:28 UTC, Fersoil commented on R/model.R
the functionality is fine, well designed implementation, but the quality of documentation needs to be improved. The general guideline of roxygen2 in R6 is [here](https://github.com/mlr-org/mlr3/wiki/Roxygen-R6-Guide)

The class object is missing fields, documentation of methods (most importantly init method) and examples

2024-08-13 16:28 UTC, Fersoil commented on R/standard_curves.R
I would also give the model a different name `SCModel` seems inconsistent with our naming, or at least the abbreviation needs to be described in the docs.
For me simply `Model` would be enough

2024-08-13 17:27 UTC, ZetrextJG commented on R/standard_curves.R
I named first named it SCLogisitcModel to indicate that we are using the Richard's model . But in the end decided that we probably will not implement many types of models. (I tried to prepare for the future, but it was not necessary ig). I will rename that

2024-08-14 11:00 UTC, Fersoil commented on R/model.R
> +    #'  Diltuions used to fit the model
```suggestion
    #'  Dilutions used to fit the model
```

2024-08-14 11:15 UTC, merged